export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';

export const ADD_TODO = 'ADD_TODO';
export const ADD_TODO_STARTED = 'ADD_TODO_STARTED';
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';

export const TOGGLE_TODO_STARTED = 'TOGGLE_TODO_STARTED';
export const TOGGLE_TODO_SUCCESS = 'TOGGLE_TODO_SUCCESS';

export const REMOVE_TODO_STARTED = 'REMOVE_TODO_STARTED';
export const REMOVE_TODO_SUCCESS = 'REMOVE_TODO_SUCCESS';

export const DELETE_TODOS_STARTED = 'DELETE_TODOS_STARTED';
export const DELETE_TODOS_SUCCESS = 'DELETE_TODOS_SUCCESS';

export const EDIT_TODO_STARTED = 'EDIT_TODO_STARTED';
export const EDIT_TODO_SUCCESS = 'EDIT_TODO_SUCCESS';

export const FETCH_TODOS = 'FETCH_TODOS';
export const FETCH_TODOS_SUCCESS = 'FETCH_TODOS_SUCCESS';
